version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: indexer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d indexer"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: indexer
      DB_PORT: 5432
      DB_SSLMODE: disable
      LOG_LEVEL: вуигп
      GRPC_ENDPOINT: http://your-grpc-url:10000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

# Define networks and volumes
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
